@baseUrl = http://localhost:3000

@apiUrl = {{baseUrl}}/api/v1

#Get request
GET {{baseUrl}}

###
POST {{apiUrl}}/Auth
Content-Type: application/json

{"username": "pat",
"email": "pat@mail.com",
"password": "123"}

###
POST {{apiUrl}}/auth/login
Content-Type: application/json

{
    "email": "pat@mail.com",
    "password": "123"
}

###
//create transactions
POST {{apiUrl}}/transactions
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBhdEBtYWlsLmNvbSIsImlhdCI6MTc1MjUwMTU3MywiZXhwIjoxNzUyNTg3OTczfQ.SQmrKoLBhIMBNnBfcOo7cnkVTWvazOPF_u2PswNqukQ

{
    "type": "income",
    "description": "youtube",
    "date": "01-01-2025",
    "amount": "555"
}

//get transactions
###
GET {{apiUrl}}/transactions
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBhdEBtYWlsLmNvbSIsImlhdCI6MTc1MjUwMTg5MywiZXhwIjoxNzUyNTg4MjkzfQ.R-fNrGygLf28GnbJJRCPONDDoQ29wdtY-PxfM4Pim4o

{
    "_id": "68748611d6799a4d1b883f1a"
}