@baseUrl = http://localhost:3000

@apiUrl = {{baseUrl}}/api/v1

#Get request
GET {{baseUrl}}

###
POST {{apiUrl}}/Auth
Content-Type: application/json

{"username": "pat",
"email": "pat@mail.com",
"password": "123"}

###
POST {{apiUrl}}/auth/login
Content-Type: application/json

{
    "email": "pat@mail.com",
    "password": "123"
}

###
POST {{apiUrl}}/transactions
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBhdEBtYWlsLmNvbSIsImlhdCI6MTc1MjQ2Nzk3MiwiZXhwIjoxNzUyNTU0MzcyfQ.e9Dx8QEuvhQevM7X7fA7hDTOiEObnnOmUQERMw4U5wI

{
    "type": "expense",
    "description": "book",
    "date": "07-10-2025",
    "amount": "4000"
}